language: csharp
dotnet: 2.0.3
mono: none
sudo: false
services:
  - 'docker'
cache:
  directories:
  - "$HOME/.nuget/"
before_install:
- set -e
script:
- "bash ./$CODEBASE/scripts/docker/build"
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    ./$CODEBASE/scripts/docker/publish;
  fi
